---
- name: "Include OS-specific e2fsprogs installation tasks"
  include_tasks: "install-e2fsprogs-{{ ansible_os_family }}.yml"

- name: "Configure Lustre server repository"
  when: lustre_manage_repo | bool
  block:
    - name: "Install Lustre server yum repo"
      yum_repository:
        name: "{{ lustre_repo_name }}"
        description: "{{ lustre_repo_description }}"
        baseurl: "{{ lustre_repo_baseurl }}"
        gpgcheck: "{{ lustre_repo_gpgcheck | default('no') }}"
        gpgkey: "{{ lustre_repo_gpgkey | default(omit) }}"
        enabled: "{{ lustre_repo_enabled | default('no') }}"
      register: _lustre_repo

    - name: "Install lustre yum repo gpgkey"
      rpm_key:
        state: present
        key: "{{ lustre_repo_gpgkey }}"
        fingerprint: "{{ lustre_repo_gpgkey_fingerprint | default(omit) }}"
      when: lustre_repo_gpgkey is defined

    - name: "Clean yum cache if repository updated (1)"
      command: yum clean all
      args:
        warn: false
      when: _lustre_repo.changed

    - name: "Clean yum cache if repository updated (2)"
      command: rm -rf /var/cache/yum
      args:
        warn: false
      when: _lustre_repo.changed

- name: "Install Lustre server packages"
  yum:
    name: "{{ lustre_server_packages }}"
    enablerepo: "{{ lustre_repo_name | default(omit) }}"
    state: present
  when: lustre_version is version('2.9.0', '>=')

- name: "Install Lustre (legacy) server packages"
  yum:
    name: "{{ lustre_server_legacy_packages }}"
    enablerepo: "{{ lustre_repo_name | default(omit) }}"
    state: present
  when: lustre_version is version('2.9.0', '<')
