---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

# PyYAML is required for this role's modules to function, we force this
# to be installed even in check-mode, since otherwise the modules will fail
- name: "Install PyYAML package"
  package:
    name: "{{ lustre_pyyaml_package }}"
    state: present
  check_mode: no

- name: "Include OS-specific e2fsprogs installation tasks"
  include_tasks: "install-e2fsprogs-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_install_e2fsprogs | bool

- name: "Include OS-specific package installation tasks"
  include_tasks: "install-server-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_install_server | bool

- name: "Include OS-specific package client installation tasks"
  include_tasks: "install-client-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'client'
    - lustre_install_client | bool

- name: "Include LNET configuration tasks"
  include_tasks: "configure-lnet.yml"

- name: "Include Start LNET tasks"
  include_tasks: "start-lnet.yml"
  when:
    - lustre_state == 'present'

- name: "Include LDISKFS formatting tasks"
  include_tasks: "format-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_format_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem mount tasks"
  include_tasks: "mount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem unmount tasks"
  include_tasks: "unmount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'absent'

- name: "Include Stop LNET tasks"
  include_tasks: "stop-lnet.yml"
  when:
    - lustre_state == 'absent'
