---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include OS-specific package installation tasks"
  include_tasks: "install-server-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_state == 'present'

- name: "Include OS-specific package client installation tasks"
  include_tasks: "install-client-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'client'
    - lustre_state == 'present'

- name: "Include LNET configuration tasks"
  include_tasks: "lnet.yml"
  when:
    - lustre_state == 'present'

- name: "Include LDISKFS formatting tasks"
  include_tasks: "format-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_format_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem mount tasks"
  include_tasks: "mount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem unmount tasks"
  include_tasks: "unmount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'absent'
