---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include OS-specific package installation tasks"
  include_tasks: "install-server-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'server'

- name: "Include LNET configuration tasks"
  include_tasks: "lnet.yml"
