---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include OS-specific package installation tasks"
  include_tasks: "install-server-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_state == 'present'

- name: "Include OS-specific package client installation tasks"
  include_tasks: "install-client-{{ ansible_os_family }}.yml"
  when:
    - lustre_install_type == 'client'
    - lustre_state == 'present'

- name: "Include LNET configuration tasks"
  include_tasks: "lnet.yml"
  when:
    - lustre_state == 'present'

- name: "Include LDISKFS formatting tasks"
  include_tasks: "format-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_format_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem mount tasks"
  include_tasks: "mount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'present'

- name: "Include LDISKFS filesystem unmount tasks"
  include_tasks: "unmount-ldiskfs.yml"
  when:
    - lustre_install_type == 'server'
    - lustre_mount_disks | bool
    - lustre_backend_filesystem == 'ldiskfs'
    - lustre_state == 'absent'

- name: "Ensure lnet service is stopped"
  service:
    name: 'lnet'
    state: 'stopped'
    enabled: true
  notify: "Unconfigure LNET"
  when:
    - lustre_state == 'absent'

- name: "Ensure lnet service is started"
  service:
    name: 'lnet'
    state: 'stopped'
    enabled: true
  when:
    - lustre_state == 'absent'

- name: "Run: lctl network unconfigure"
  command: "lctl network unconfigure"
  register: result
  changed_when: "result.rc == 0 and ('LNET ready to unload' in result.stderr)"
  failed_when: false
  check_mode: no
  when:
    - lustre_state == 'absent'

- name: "Run: lustre_rmmod"
  command: "lustre_rmmod"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no
  when:
    - lustre_state == 'absent'
