---
- name: "Restart LNET"
  service:
    name: "lnet"
    state: "restarted"

- name: "Unconfigure LNET"
  debug: msg="Unconfiguring lnet and then removing all lustre modules"
  changed_when: True
  notify:
    - "Run: lctl network unconfigure"
    - "Run: lustre_rmmod"

- name: "Run: lctl network unconfigure"
  command: "lctl network unconfigure"
  register: result
  changed_when: "result.rc == 0 and ('LNET ready to unload' in result.stderr)"
  failed_when: "result.rc != 0"
  ignore_errors: yes
  check_mode: no

- name: "Run: lustre_rmmod"
  command: "lustre_rmmod"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no
